---
title: "Project 2 Data Cleaning"
author: "Matt Johnson"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
Read in data from kaggle: https://www.kaggle.com/tobycrabtree/nfl-scores-and-betting-data?select=nfl_teams.csv
```{r}
Game.Results <- read.csv("Source-Data/spreadspoke_scores.csv") %>% 
  filter(schedule_season >= 2000)
Team.Info <- read.csv("Source-Data/nfl_teams.csv")
write.csv(Game.Results, "Source-Data/Game.Results.csv")
```

Read in Offenseive Aggregate Data from: https://www.pro-football-reference.com
```{r}
Offense.Stats2000 <- read.csv("Source-Data/P2.2000.Off.Stats.csv")
Offense.Stats2001 <- read.csv("Source-Data/P2.2001.Off.Stats.csv")
Offense.Stats2002 <- read.csv("Source-Data/P2.2002.Off.Stats.csv")
Offense.Stats2003 <- read.csv("Source-Data/P2.2003.Off.Stats.csv")
Offense.Stats2004 <- read.csv("Source-Data/P2.2004.Off.Stats.csv")
Offense.Stats2005 <- read.csv("Source-Data/P2.2005.Off.Stats.csv")
Offense.Stats2006 <- read.csv("Source-Data/P2.2006.Off.Stats.csv")
Offense.Stats2007 <- read.csv("Source-Data/P2.2007.Off.Stats.csv")
Offense.Stats2008 <- read.csv("Source-Data/P2.2008.Off.Stats.csv")
Offense.Stats2009 <- read.csv("Source-Data/P2.2009.Off.Stats.csv")
Offense.Stats2010 <- read.csv("Source-Data/P2.2010.Off.Stats.csv")
Offense.Stats2011 <- read.csv("Source-Data/P2.2011.Off.Stats.csv")
Offense.Stats2012 <- read.csv("Source-Data/P2.2012.Off.Stats.csv")
Offense.Stats2013 <- read.csv("Source-Data/P2.2013.Off.Stats.csv")
Offense.Stats2014 <- read.csv("Source-Data/P2.2014.Off.Stats.csv")
Offense.Stats2015 <- read.csv("Source-Data/P2.2015.Off.Stats.csv")
Offense.Stats2016 <- read.csv("Source-Data/P2.2016.Off.Stats.csv")
Offense.Stats2017 <- read.csv("Source-Data/P2.2017.Off.Stats.csv")
Offense.Stats2018 <- read.csv("Source-Data/P2.2018.Off.Stats.csv")
Offense.Stats2019 <- read.csv("Source-Data/P2.2019.Off.Stats.csv")
Offense.Stats2020 <- read.csv("Source-Data/P2.2020.Off.Stats.csv")
```

Read in Defensive Aggregate Data from: https://www.pro-football-reference.com
```{r}
Defense.Stats2000 <- read.csv("Source-Data/P2.2000.Def.Stats.csv")
Defense.Stats2001 <- read.csv("Source-Data/P2.2001.Def.Stats.csv")
Defense.Stats2002 <- read.csv("Source-Data/P2.2002.Def.Stats.csv")
Defense.Stats2003 <- read.csv("Source-Data/P2.2003.Def.Stats.csv")
Defense.Stats2004 <- read.csv("Source-Data/P2.2004.Def.Stats.csv")
Defense.Stats2005 <- read.csv("Source-Data/P2.2005.Def.Stats.csv")
Defense.Stats2006 <- read.csv("Source-Data/P2.2006.Def.Stats.csv")
Defense.Stats2007 <- read.csv("Source-Data/P2.2007.Def.Stats.csv")
Defense.Stats2008 <- read.csv("Source-Data/P2.2008.Def.Stats.csv")
Defense.Stats2009 <- read.csv("Source-Data/P2.2009.Def.Stats.csv")
Defense.Stats2010 <- read.csv("Source-Data/P2.2010.Def.Stats.csv")
Defense.Stats2011 <- read.csv("Source-Data/P2.2011.Def.Stats.csv")
Defense.Stats2012 <- read.csv("Source-Data/P2.2012.Def.Stats.csv")
Defense.Stats2013 <- read.csv("Source-Data/P2.2013.Def.Stats.csv")
Defense.Stats2014 <- read.csv("Source-Data/P2.2014.Def.Stats.csv")
Defense.Stats2015 <- read.csv("Source-Data/P2.2015.Def.Stats.csv")
Defense.Stats2016 <- read.csv("Source-Data/P2.2016.Def.Stats.csv")
Defense.Stats2017 <- read.csv("Source-Data/P2.2017.Def.Stats.csv")
Defense.Stats2018 <- read.csv("Source-Data/P2.2018.Def.Stats.csv")
Defense.Stats2019 <- read.csv("Source-Data/P2.2019.Def.Stats.csv")
Defense.Stats2020 <- read.csv("Source-Data/P2.2020.Def.Stats.csv")
```


